### ISSUE TITLE
busybox 1.31.9-r1 has a vulnerability

### ISSUE THREAD

**Issue by consult-kk** [alpinelinux/docker-alpine#101]
Please address the following vulnerabilities : 

Busybox - CVE-2018-1000500
PCRE pkg - CVE-2020-14155

or provide ability to upgrade these packages

**Comment by ncopa** [comment]
CVE-2018-1000500 was fixed in alpinelinux/aports@1d0560a9b6b5597b191e5aff69a31c2fe0aba273 (busybox 1.28.3-r2 in edge)

**Comment by DamasFoux** [comment]
Will be there a new version from alpine 3.12 to fix this issue?

**Comment by ncopa** [comment]
no new version because 3.12 was never affected. It was fixed in 2018, before 3.12 was released.

I updated the secfixes comment (alpinelinux/aports@87bc1a582e98b269bbd75646d6373b1be710ef45) so scanners have a chance to pick it up.

the PCRE issue CVE-2020-14155 still needs investigation but is not related to busybox which this issue is about.

**Comment by ncopa** [comment]
the unrelated pcre issue was fixed before 3.12 was released in commit alpinelinux/aports@47b52e878e5d803ceb888a1404a311e19f30cb6e

I'm sorry that I don't have time or energy to fix all broken security scanners out there.

**Comment by DamasFoux** [comment]
@ncopa many thanks for your confirmation!
