### ISSUE TITLE
alpine images has CVE-2021-31535

### ISSUE THREAD

**Issue by seekjp** [alpinelinux/docker-alpine#187]
https://nvd.nist.gov/vuln/detail/CVE-2021-31535

LookupCol.c in X.Org X through X11R7.7 and libX11 before 1.7.1 might allow remote attackers to execute arbitrary code. The libX11 XLookupColor request (intended for server-side color lookup) contains a flaw allowing a client to send color-name requests with a name longer than the maximum size allowed by the protocol (and also longer than the maximum packet size for normal-sized packets). The user-controlled data exceeding the maximum size is then interpreted by the server as additional X protocol requests and executed, e.g., to disable X server authorization completely. For example, if the victim encounters malicious terminal control sequences for color codes, then the attacker may be able to take full control of the running graphical session.

**Comment by ncopa** [comment]
We don't ship libx11 in alpine docker image, so this should have been reported to https://gitlab.alpinelinux.org/alpine/aports/-/issues

That said, seems like we fixed this CVE in May 2021.

fixed in:
- 3.14: alpinelinux/aports@188ea1adfba09d5b632ab1309aa57f9141858b70
- 3.13: alpinelinux/aports@da91dd08011130df37a0a7b5332af0b4b60062f7
- 3.12: alpinelinux/aports@721ca84683a67b31dcc8576d5a221fc32ac3b45f
- 3.11: alpinelinux/aports@d7d347476ce810f36f6376884be16781f79d3006
