### ISSUE TITLE
CVE-2019-12900

### ISSUE THREAD

**Issue by codeitsfun** [alpinelinux/docker-alpine#22]
CVE-2019-12900 has been reported and probably also affects alpine

**Comment by markdenihan** [comment]
This CVE is being reported by container scanners. Is there any plan to pick up the fix?

**Comment by ncopa** [comment]
> This CVE is being reported by container scanners. Is there any plan to pick up the fix?

Yes. Should be fixed now.

**Comment by ncopa** [comment]
fixed with alpinelinux/aports@53b02f8b1597aabb4ec836bb5aa421e0d1f95189 (edge), alpinelinux/aports@f47a9e1da5b7f33cf5d46c0541deb454729eee51 (3.10), alpinelinux/aports@d8ead9ace841cece4ee4f90c91900ea12aecb759 (3.9), alpinelinux/aports@48ec283be13e799c70aae6c045c2c93e39d262a0 (3.8) and alpinelinux/aports@263042b4f11c9dbc797bdf7eef8c0ebdda9efe4a (3.7)
