### ISSUE TITLE
Missing packages from version `3.19`

### ISSUE THREAD

**Issue by StamenchoBog** [alpinelinux/docker-alpine#364]
Hello,

As I can see from docker hub, the docker image for Alpine got a new release `3.19`, 4 days ago and a lot of packages are missing that where present in the previous version.

**Problem explanation**:  We are using this docker Alpine image to run some CI scripts. In order to properly run the CI scripts we are installing dependencies in the Alpine docker container. One of those images is the image `packer` which was present in version `3.18`, but it is not in version `3.19`. You can view the error on the picture below.

**Temporary resolution**: In order to overcome this we reverted to the previous Alpine version `3.18`.

![Screenshot 2023-12-12 at 10 42 41](https://github.com/alpinelinux/docker-alpine/assets/73882878/fe561c98-d3b6-4919-9643-ab6299ed5d42)

Can you guys check what might be the issue and notify me ?

Thank you,
Stamencho

**Comment by MichaelGerhart** [comment]
This is by design,

Hashicorp's unfortunate licensing changes have forced open source projects to stop supporting Hashicorp's products.

Please look at the release notes for Alpine 3.19: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.19.0

![image](https://github.com/alpinelinux/docker-alpine/assets/5455211/72e6efde-979a-4547-a89c-1a59b2f7ed3d)

**Comment by StamenchoBog** [comment]
Hey @MichaelGerhart thank you for the response and clarification. Will keep using the `3.18` until maybe I will try to switch because of the need for Packer at the moment.

**Note**: I completely support these kind of actions that support open-source communities and boycott the opposite actions (in this case HashiCorp).
