### ISSUE TITLE
alpine:latest has CVE-2019-1563,CVE-2019-1549,CVE-2019-1547 for libssl1.1 and libcrypto1.1

### ISSUE THREAD

**Issue by tgerlach** [alpinelinux/docker-alpine#39]
```
Vulnerable Packages Found
=========================

Vulnerability ID   Policy Status   Affected Packages         How to Resolve
CVE-2019-1547      Active          libssl1.1, libcrypto1.1   Upgrade 2 packages. Re-run command with --extended to view.
CVE-2019-1549      Active          libssl1.1, libcrypto1.1   Upgrade 2 packages. Re-run command with --extended to view.
CVE-2019-1563      Active          libssl1.1, libcrypto1.1   Upgrade 2 packages. Re-run command with --extended to view.
```

extended view for resolution

```
   Vendor Security Notice IDs   Official Notice
   ALPINE-CVE-2019-1547

   Affected Packages   Policy Status   How to Resolve                         Security Notice
   libssl1.1           Active          Upgrade libssl1.1 to >= 1.1.1d-r1      ALPINE-CVE-2019-1547
   libcrypto1.1        Active          Upgrade libcrypto1.1 to >= 1.1.1d-r1   ALPINE-CVE-2019-1547

```

```
   Vendor Security Notice IDs   Official Notice
   ALPINE-CVE-2019-1549

   Affected Packages   Policy Status   How to Resolve                         Security Notice
   libssl1.1           Active          Upgrade libssl1.1 to >= 1.1.1d-r1      ALPINE-CVE-2019-1549
   libcrypto1.1        Active          Upgrade libcrypto1.1 to >= 1.1.1d-r1   ALPINE-CVE-2019-1549
```

```
  Vendor Security Notice IDs   Official Notice
   ALPINE-CVE-2019-1563

   Affected Packages   Policy Status   How to Resolve                         Security Notice
   libssl1.1           Active          Upgrade libssl1.1 to >= 1.1.1d-r1      ALPINE-CVE-2019-1563
   libcrypto1.1        Active          Upgrade libcrypto1.1 to >= 1.1.1d-r1   ALPINE-CVE-2019-1563
```

**Comment by tgerlach** [comment]
mistake opening here - looking at wrong vulnerability report

**Comment by ncopa** [comment]
Will try get a new release ASAP. Meanwhile, you can run `apk upgrade -U -a` as workaround.

**Comment by tgerlach** [comment]
thanks @ncopa I had already tried that but it only took me to `1.1.1d-r0`

```
Step 2/3 : RUN apk update && apk upgrade -U -a
 ---> Running in 18e9b7a5a0ba
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.2-55-g6cecf3cc9d [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.2-42-g95d37f7648 [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10336 distinct packages available
(1/2) Upgrading libcrypto1.1 (1.1.1c-r0 -> 1.1.1d-r0)
(2/2) Upgrading libssl1.1 (1.1.1c-r0 -> 1.1.1d-r0)
OK: 6 MiB in 14 packages
```

**Comment by tgerlach** [comment]
@ncopa any status update for having new release with updated packages??

**Comment by ncopa** [comment]
I was supposed to do it today, but I want squeeze in a few more kernel changes. I will try get the release out early next week

**Comment by tgerlach** [comment]
@ncopa I guess here is my weekly request of update status, again :-)

**Comment by strouja** [comment]
Whatever you can to get this done by early next week or even this weekend (I'm writing this on Oct 4, 2019) is critical for us.  We are trying to release our product using alpine (I'm a big advocate for it at IBM) but we can't ship until we included these fixes.  So I have a vested interest in getting these two packages patched.  Thanks for you help with this, James Stroud IBM

**Comment by cobu2b** [comment]
Is this change ready? I hope that I can use this fix to resolve the reported vulnerabilities in our products soon. Thank you

**Comment by jdkelley** [comment]
@cobu2b - Currently, [alpine:3.10.3](https://hub.docker.com/_/alpine) is on Docker Hub as `latest` and includes OpenSSL 1.1.1d-r0 which is patched for 

* CVE-2019-1563
* CVE-2019-1549
* CVE-2019-1547

It looks like this issue could be closed.

**Comment by cobu2b** [comment]
Thank you @jdkelley. When I use `FROM alpine:latest` or `FROM alpine`, an image picks up Alpine 3.10.2 instead of 3.10.3. Is it expected? When I use `FROM alpine:3.10.3`, I can see OpenSSL 1.1.1d-r0 as expected. I try to avoid specifying the alpine version and use the stable image only. Could you please give me advice? Thank you

**Comment by jdkelley** [comment]
Interesting @cobu2b. I can't reproduce that. Have you tried clearing the old images out before building again? You can do this with `docker rmi $(docker images -aq)` (*CAUTION: this will remove all docker images you have locally.*)

When I check the version of Alpine in the `alpine:latest` container it is the same as the version in `alpine:3.10.3`.

`alpine:latest`:

```
$ docker run alpine:latest cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

`alpine:3.10.3`:

```
$ docker run alpine:3.10.3 cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

Similarly, using each of these images as a base image, I get the same result.

* With `alpine:latest`:

```
$ cat > Dockerfile <<EOF
> FROM alpine:latest
> RUN cat /etc/os-release
> EOF
$ 
$ docker build .
Sending build context to Docker daemon  126.5kB
Step 1/2 : FROM alpine:latest
 ---> 965ea09ff2eb
Step 2/2 : RUN cat /etc/os-release
 ---> Running in 5d302b63bf67
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
Removing intermediate container 5d302b63bf67
 ---> a7d2d692b963
Successfully built a7d2d692b963
```

* With `alpine:3.10.3`:

```
$ cat > Dockerfile <<EOF
> FROM alpine:3.10.3
> RUN cat /etc/os-release
> EOF
$
$ docker build .
Sending build context to Docker daemon  126.5kB
Step 1/2 : FROM alpine:3.10.3
 ---> 965ea09ff2eb
Step 2/2 : RUN cat /etc/os-release
 ---> Running in ef9fda68f8ab
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
Removing intermediate container ef9fda68f8ab
 ---> 07b8cbbd22e9
Successfully built 07b8cbbd22e9
```

---

Of Note:

I have found that using `latest` doesn't always behave the way I would expect. Docker doesn't go out and check that the image you have tagged as `latest` locally is actually the latest on Docker Hub. So, if you already have an image tagged with `alpine:latest` locally, your docker client will use that image. 

To ensure you have the latest `latest`, run `docker pull alpine:latest`. You can make sure your build command does this by passing the `--build` flag to your `docker build` command (reference: [docker build](https://docs.docker.com/engine/reference/commandline/build/)).

**Comment by cobu2b** [comment]
Thank you so much for your help, Joshua. Actually it happened as you described. My local alpine:latest is old. Running `docker pull alpine:latest` and rebuilding the image help.

**Comment by ncopa** [comment]
Updates are on their way: https://github.com/docker-library/official-images/pull/7331

Those issues was fixed long time ago in the packages and it has always been possible to get those fixes with `apk upgrade`.

In any case, sorry for taking so long, and thank you for your patience.

**Comment by ingokofler** [comment]
@ncopa Thanks! 

Is this considered as best-practice to run `apk upgrade` in the Dockerfiles when building on top of alpine linux? 
In the case of the alpine-based images we use I haven't seen this in the corresponding Dockerfiles... It seems that they are relying somehow that the alpine images are maintained and up-to-date.

**Comment by J0WI** [comment]
> Avoid RUN `apt-get upgrade` and `dist-upgrade`, as many of the “essential” packages from the parent images cannot upgrade inside an unprivileged container. If a package contained in the parent image is out-of-date, contact its maintainers. If you know there is a particular package, foo, that needs to be updated, use `apt-get install -y foo` to update automatically.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get

**Comment by redbelow** [comment]
getting this with alpine 3.12.2 as well, see below

 trivy image alpine:latest
2020-12-15T13:06:34.066-0600	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2020-12-15T13:06:35.831-0600	INFO	Detecting Alpine vulnerabilities...
2020-12-15T13:06:35.832-0600	INFO	Trivy skips scanning programming language libraries because no supported file was detected

alpine:latest (alpine 3.12.2)
=============================
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 2, CRITICAL: 0)

+--------------+------------------+----------+-------------------+---------------+--------------------------------+-----------------------------------+
|   LIBRARY    | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |             TITLE              |                URL                |
+--------------+------------------+----------+-------------------+---------------+--------------------------------+-----------------------------------+
| libcrypto1.1 | CVE-2020-1971    | HIGH     | 1.1.1g-r0         | 1.1.1i-r0     | The X.509 GeneralName          | avd.aquasec.com/nvd/cve-2020-1971 |
|              |                  |          |                   |               | type is a generic type         |                                   |
|              |                  |          |                   |               | for representing different     |                                   |
|              |                  |          |                   |               | types...                       |                                   |
+--------------+                  +          +                   +               +                                +                                   +
| libssl1.1    |                  |          |                   |               |                                |                                   |
|              |                  |          |                   |               |                                |                                   |
|              |                  |          |                   |               |                                |                                   |
|              |                  |          |                   |               |                                |                                   |
+--------------+------------------+----------+-------------------+---------------+--------------------------------+-----------------------------------+
