### ISSUE TITLE
New image pushed for tag 3.20.3?

### ISSUE THREAD

**Issue by thomasleplus** [alpinelinux/docker-alpine#424]
Hello,

I received a notification that a new image was pushed for tag 3.20.3 in Docker Hub. I would just like to get a confirmation that it is a legitimate update (since I believe it's unusual for this project to overwrite the image for an existing tag instead of bumping the tag version)?

Also is there an official page or a mailing list where such things are announced so that I can check by myself next time?

Thank you for maintaining these images.

Regards,

Thomas

**Comment by sjrulandch** [comment]
I have the same question.

Something seems wrong with the Alpine containers. 
I have 8 or so services running under docker compose (win 10, 4.34.3/4.35.1).
They had been running fine for about 9 days until the machine needed a reboot.
On restart, all of the Alpine based containers failed on images pull with various versions of
`failed on /var/lib/desktop-containerd/daemon/tmpmounts/containerd-mount` or
`failed to solve: failed to compute cache key: mount callback failed`

After a bunch of trial and error, I discovered that RabbitMQ had images for both Alpine and Ubuntu. Simply switching to the image tag and everything resumed working.

In researching this, it seems like the failure is happening when the dockerfile is trying to `ADD`, `COPY` or otherwise inject configuration. In my RMQ example, it seemed to be failing to inject an extra plugin as well as a conf file.

Most of my containers are third party. Doubt I will be as lucky as RMQ.

PS: RMQ was using Alpine 3.20.3 and the tag was set 2024-11-11. It appears that ALL of the Alpine containers were tagged that day but GH changes were a month older.

**Comment by thomasleplus** [comment]
3.21.0 was just released so I will upgrade and close this issue. It would have been nice to get an answer though. Anyway thanks again for all the hard work.

@sjrulandch feel free to reopen this issue if your problem persists in 3.21.0.
