### ISSUE TITLE
alpine:edge cant install packages

### ISSUE THREAD

**Issue by SteveOzo** [alpinelinux/docker-alpine#49]
Actually image alpine:edge can run apk update or apk add.

`/ # apk update

fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
WARNING: Ignoring APKINDEX.066df28d.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
WARNING: Ignoring APKINDEX.b53994b4.tar.gz: No such file or directory
2 errors; 14 distinct packages available

/ # apk add --no-cache curl

fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
curl (missing):
required by: world[curl]`

**Comment by beyang** [comment]
Workaround: use one of the other mirrors: https://mirrors.alpinelinux.org/

**Comment by test482** [comment]
I got same problem, fixed by change mirrors list.

**Comment by melissaettinger** [comment]
We are also getting the issue with nl.alpinelinux.org

fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz: No such file or directory
WARNING: Ignoring http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz: No such file or directory
WARNING: The repository tag for world dependency 'chromium@edge' does not exist
WARNING: The repository tag for world dependency 'nss@edge' does not exist
WARNING: The repository tag for world dependency 'freetype@edge' does not exist
WARNING: The repository tag for world dependency 'harfbuzz@edge' does not exist
WARNING: The repository tag for world dependency 'ttf-freefont@edge' does not exist
ERROR: Not committing changes due to missing repository tags. Use --force-broken-world to override.
The command '/bin/sh -c if [ "$tests" = "true" ] ;then     apk update && apk upgrade &&     echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories &&     echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories &&     apk add --no-cache       chromium@edge=72.0.3626.121-r0       nss@edge       freetype@edge       harfbuzz@edge       ttf-freefont@edge     ; fi' returned a non-zero code: 99
##[error]The command '/bin/sh -c if [ "$tests" = "true" ] ;then     apk update && apk upgrade &&     echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories &&     echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories &&     apk add --no-cache       chromium@edge=72.0.3626.121-r0       nss@edge       freetype@edge       harfbuzz@edge       ttf-freefont@edge     ; fi' returned a non-zero code: 99
##[error]/usr/bin/docker failed with return code: 99


If you look at http://nl.alpinelinux.org/alpine/edge/main/ the folder for x86_64 has been removed and the repository was updated last night. 

For http://nl.alpinelinux.org/alpine/edge/community/ the folder for x86_64 exists but is now empty, also updated last night.

**Comment by dunielpls** [comment]
It's a known problem and it's currently in the process of being fixed.

**Comment by bceskavich** [comment]
Looks like the `x86_64` directory is back and fully populated on the CDN and at least one mirror: 

- http://nl.alpinelinux.org/alpine/edge/main/
- http://dl-cdn.alpinelinux.org/alpine/edge/main/
