### ISSUE TITLE
ncurses version number format

### ISSUE THREAD

**Issue by mraiur** [alpinelinux/docker-alpine#68]
Hello we are running a twistlock scan on one of our projects. It fails for ncurses pacakge and i assume its because the way it parses the version.

In the docker repository for 3.11 the versions is 6.1**_p**2019**1130**-r0 and not something like 6.1.20191130-r0 is this a bug or intended ? 

The affected versions are bellow 6.1.2019**1012**

[CVE-2019-17595](https://nvd.nist.gov/vuln/detail/CVE-2019-17595)
[Alpine aports ncurses version commit](https://git.alpinelinux.org/aports/commit/?id=8188fe63eff65b2b65874a2aad80959df47a8443)

**Comment by ncopa** [comment]
This was intentional. There are no upstream 6.1.20191012 release, there is only a 6.1 release and a patch with 20191012. See the https://lists.gnu.org/archive/html/bug-ncurses/2019-10/msg00045.html that is in the reference.

Gentoo has similar version format for ncurses: https://packages.gentoo.org/packages/sys-libs/ncurses

**Comment by mraiur** [comment]
I understand. Thank you for the information and the links. Have a great day!
