### ISSUE TITLE
bzr is not available in alpline:3.12

### ISSUE THREAD

**Issue by yelizariev** [alpinelinux/docker-alpine#87]
Docker file:
```

FROM alpine

RUN apk update && apk add bzr

```

**Comment by ncopa** [comment]
was removed in commit alpinelinux/aports@ac31bbdef70848506123572db93edc4a6260d040 due to python2 dependency.

Please [create an upstream issue]( https://gitlab.alpinelinux.org/alpine/aports/-/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=) on alpine linux's gitlab where you request addition of `breezy` if you still need bzr.
