### ISSUE TITLE
shell: No errors when shifting more than number of shell arguments

### ISSUE THREAD

**Issue by atyutyunnik** [alpinelinux/docker-alpine#96]
If I run shell with just one argument while shifting argments by 2, the run command will be in an endless cycle:
```docker build -t alpine-tmp .```
```docker run alpine-tmp .```

Expected behavior: shift shell arguments to zero and leave the cycle.

Even if I have "set -e" (interrupt on error), the whole shell script will finish, but without any indication error message

Dockerfile:
```
FROM alpine
copy ./script.sh ./script.sh
RUN chmod a+x script.sh
ENTRYPOINT [ "./script.sh" ]
```
script.sh:
```
#!/bin/sh
set -vx;

while [ "$#" -gt 0 ];
do
        shift 2;
done

```

**Comment by ncopa** [comment]
> Expected behavior: shift shell arguments to zero and leave the cycle.

That is wrong. According [POSIX]( https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#shift) the expected behavior is:

> EXIT STATUS
> If the n operand is invalid or is greater than "$#", this may be considered a syntax error and a non-
> interactive shell may exit; if the shell does not exit in this case, a non-zero exit status shall be
> returned. Otherwise, zero shall be returned.

which is exactly what you are seeing. When you shift a bigger number than arguments it returns non-zero (error).

> Even if I have "set -e" (interrupt on error), the whole shell script will finish, but without any indication error message

This indicates that `shift 2` does return error status (but no error message).

This would be the proper way to do what you are requesting:
```sh
while [ $# -gt 0 ]; do
  shift 2 || shift # do a single `shift` if `shift 2` fails
done
```
